### ISSUE TITLE
Values from metrics not getting pushed by pusher in combination with AWS Lambda

### ISSUE THREAD

**Issue by patrickvastenhouw** [PrometheusClientNet/Prometheus.Client.MetricPusher#10]
Hello,

I'm having an AWS Lambda in which I like to add some custom metrics and push the data to Prometheus.

The Lambda is very simple. It calls an API endpoint and receives data.

The problem I'm having is that no values appear of metrics inside Prometheus, but the metrics did get created. I create a pushserver, add a couple of counter metrics, start the server and finally stop the server when the AWS Lambda is done doing what it needs to do.

Output in Prometheus:
[https://ibb.co/brvzT33](https://ibb.co/brvzT33)

My code is looking like this:

```
private IMetricPushServer _metricsPushServer;

public async Task<T> FunctionHandler(ILambdaContext context)
{
    try
    {
        var registry = new CollectorRegistry();
        var factory = new MetricFactory(registry);
        var pusher = new MetricPusher(registry, "some endpoint", "some name", "some id", labels, null);
        _metricsPushServer = new MetricPushServer(new IMetricPusher[] { pusher });
        var testCounter = factory.CreateCounter("test", "this is a test");
        
         _metricsPushServer.Start();
        
        //calls API endpoint
        
        testCounter.Inc();
    }
    catch
    {
        //error handling
    }
    finally
    {
         _metricsPushServer.Stop();
    }
}
```

Anyone has any idea what I could do differently or try out etc.?

**Comment by sanych-sun** [comment]
Metrics are not appears on Prometheus, because pushserver does not have a chance to push them... as it pushes metrics with some timeout, but you stops the server immediately when your unit of work is done.

For such use cases it might makes sense to use IPusher directly:
1) Create registry and factory (as you already done)
2) Create metrics and use it 
3) Create MetricPusher by providing registry and Prometheus push gateway
4) When your unit of work is done - use PushAsync to send the metrics

**Comment by patrickvastenhouw** [comment]
Makes sense. The Lambda only takes a couple of seconds to complete it's run. So timing may be an issue here.

Unfortunately I can't verify if your possible solution works. Due to changes in project setup we don't need the Lambda anymore. Therefore I'm closing this issue.

Thanks for your time!
